# Documentation: https://gohugo.io/getting-started/configuration/

baseURL = "https://mitsuyoshi-yamazaki.github.io"
languageCode = "ja-jp"
title = "みつよし手稿"
description = ""
theme = "paper"

googleAnalytics = "G-3EB73WSJ9K"

staticDir = "static"

# ---- Site Settings ---- #
[menu]
  [[menu.main]]
    name = "検索"
    url = "search/"
    weight = 10
  [[menu.main]]
    name = "投稿一覧"
    url = "posts/"
    weight = 20
  [[menu.main]]
    name = "タグ"
    url = "tags/"
    weight = 30


# ---- Markup ---- #
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true # 改行を改行と認識する
      unsafe = true # 生HTMLの描画


# ---- In Site Search ---- #
# https://github.com/adityatelange/hugo-PaperMod/wiki/Features#search-page
[outputs]
  home = [
    "HTML", 
    "RSS",
    "JSON"  # is necessary
    ]


# ---- Theme Settings ---- #
[params]
  # PaperMod
  [params.homeInfoParams]
    title = "みつよし手稿"
    content = """
ものづくりと観察が好きです

---
製作物
・人工生命をベースとしたジェネラティブアート: [Gallery - ALifeLab](https://mitsuyoshi-yamazaki.github.io/ALifeLab/pages/gallery.html)
・人工生命分野関連のweb新聞: [ALife Newsletter](https://alife.org/category/newsletter/)
・[Factorio Mods](https://mods.factorio.com/user/mitsuyoshi)
・外部ブログ：
　・[note](https://note.com/_mitsuyoshi)
　・[Zenn](https://zenn.dev/mitsuyoshi)
    """

  [[params.socialIcons]]
    name = "Twitter"
    url = "https://twitter.com/vespid"
  [[params.socialIcons]]
    name = "GitHub"
    url = "https://github.com/mitsuyoshi-yamazaki"

  [params.fuseOpts] # 検索
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 0
    keys = ["title", "permalink", "summary", "content"]


# ---- Language ---- #
# https://gohugo.io/content-management/multilingual/#configure-languages
defaultContentLanguage = "ja-jp"
[languages]
  [languages.ja-jp]
    # デフォルト設定と同一の値は省略
    languageName = "日本語"
    weight = 1
  [languages.en]
    languageName = "English"
    weight = 2
    title = "Mitsuyoshi's Manuscript"
    description = ""
    staticDir1 = "static_en"
    [languages.en.params.homeInfoParams]
      title = "Mitsuyoshi's Manuscript"
      content = """
I love emergence

---
What I made:
・Artificial life based generative arts: [Gallery - ALifeLab](https://mitsuyoshi-yamazaki.github.io/ALifeLab/pages/gallery.html)
・web newsletter on Artificial life field: [ALife Newsletter](https://alife.org/category/newsletter/)
・[Factorio Mods](https://mods.factorio.com/user/mitsuyoshi)
・blogs/articles：
　・[note](https://note.com/_mitsuyoshi)
　・[Zenn](https://zenn.dev/mitsuyoshi)
    """

    [languages.en.menu]
      [[languages.en.menu.main]]
        name = "Search"
        url = "search/"
        weight = 10
      [[languages.en.menu.main]]
        name = "Posts"
        url = "posts/"
        weight = 20
      [[languages.en.menu.main]]
        name = "Tags"
        url = "tags/"
        weight = 30
