baseURL = "https://mitsuyoshi-yamazaki.github.io"
languageCode = "ja-jp"
title = "みつよし手稿"
theme = "paper"

googleAnalytics = "G-3EB73WSJ9K"

[[menu.posts]]
identifier = "posts"
name = "posts"
url = "/posts/"
weight = 10
