# Documentation: https://gohugo.io/getting-started/configuration/

baseURL = "https://mitsuyoshi-yamazaki.github.io"
languageCode = "ja-jp"
title = "みつよし手稿"
theme = "paper"

googleAnalytics = "G-3EB73WSJ9K"

# ---- Language ---- #
# https://gohugo.io/content-management/multilingual/#configure-languages
defaultContentLanguage = "ja-jp"
[languages]
  [languages.ja-jp]
    # デフォルト言語なので空
  [languages.en]
    title = "Mitsuyoshi's Manuscript"
    [languages.en.params.homeInfoParams]
      title = "Mitsuyoshi's Manuscript"

# ---- Site Settings ---- #
[[menu.posts]]
  identifier = "posts"
  name = "posts"
  url = "/posts/"
  weight = 10

# ---- Markup ---- #
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true # 改行を改行と認識する

# ---- Theme Settings ---- #
[params]
  # PaperMod
  [params.homeInfoParams]
    title = "みつよし手稿"
#    content = "Can be Info, links, about..." # TODO:

  [[params.socialIcons]]
    name = "Twitter"
    url = "https://twitter.com/vespid"
  [[params.socialIcons]]
    name = "GitHub"
    url = "https://github.com/mitsuyoshi-yamazaki"
